---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: <<PROJECT>>
      auth:
        secretRef:
          secretAccessKeySecretRef:
            namespace: <<NS>>
            name: gcp-secret-manager              # secret name containing SA key
            key: gcp-creds.json
